# This workflow installs dependencies, caches them, builds, tests, and deploys a React app to GitHub Pages.

name: React CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]  # Based on compatibility with dependencies like React 18.x and your package.json

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install --force  # Forces install of dependencies to ensure compatibility

    - run: npm ci  # Installs dependencies from package-lock.json for consistent builds

    - run: npm run build --if-present  # Builds the React app

    - run: npm test  # Runs tests, ensure your test suite is set up in your React project

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Specifies Node.js version for deployment

    - name: Install dependencies
      run: npm ci

    - name: Build the React app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Points to the build directory for deployment
